// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	entity "digital-signature/entity"

	mock "github.com/stretchr/testify/mock"
)

// SignatureRepository is an autogenerated mock type for the SignatureRepository type
type SignatureRepository struct {
	mock.Mock
}

// Find provides a mock function with given fields: id
func (_m *SignatureRepository) Find(id uint) (*entity.Signature, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 *entity.Signature
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*entity.Signature, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *entity.Signature); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Signature)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: _a0
func (_m *SignatureRepository) Save(_a0 *entity.Signature) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.Signature) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSignatureRepository creates a new instance of SignatureRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSignatureRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SignatureRepository {
	mock := &SignatureRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
