// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CertificateAuthority is an autogenerated mock type for the CertificateAuthority type
type CertificateAuthority struct {
	mock.Mock
}

// Enroll provides a mock function with no fields
func (_m *CertificateAuthority) Enroll() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Enroll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Renew provides a mock function with no fields
func (_m *CertificateAuthority) Renew() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Renew")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Revoke provides a mock function with no fields
func (_m *CertificateAuthority) Revoke() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Revoke")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Status provides a mock function with no fields
func (_m *CertificateAuthority) Status() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCertificateAuthority creates a new instance of CertificateAuthority. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCertificateAuthority(t interface {
	mock.TestingT
	Cleanup(func())
}) *CertificateAuthority {
	mock := &CertificateAuthority{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
